# Generated by Django 4.1.4 on 2022-12-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact",
            old_name="date_of_birth",
            new_name="birth_date",
        ),
    ]
