# Generated by Django 4.1.4 on 2022-12-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("crm", "0004_alter_company_options_contact_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="portal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sites.site",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="portal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sites.site",
            ),
        ),
    ]
