# Generated by Django 4.1.4 on 2022-12-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("crm", "0005_company_portal_contact_portal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="portal",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="portal",
        ),
        migrations.AddField(
            model_name="company",
            name="portals",
            field=models.ManyToManyField(to="sites.site"),
        ),
        migrations.AddField(
            model_name="contact",
            name="portals",
            field=models.ManyToManyField(to="sites.site"),
        ),
    ]
