# Generated by Django 4.1.4 on 2022-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_remove_company_portal_remove_contact_portal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="extra",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="extra",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
