# Generated by Django 4.1.4 on 2022-12-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_alter_company_extra_alter_contact_extra_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="extra",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="contact",
            name="extra",
            field=models.JSONField(default=dict),
        ),
    ]
