# Generated by Django 4.1.4 on 2022-12-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_company_extra_alter_contact_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='contact',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='extrafieldschema',
            name='schema',
            field=models.JSONField(),
        ),
    ]
