# Generated by Django 4.1.4 on 2022-12-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("crm", "0013_alter_company_extra_alter_contact_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrafieldschema",
            name="portals",
            field=models.ManyToManyField(blank=True, to="sites.site"),
        ),
    ]
