# Generated by Django 4.1.4 on 2022-12-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0001_initial"),
        ("crm", "0014_alter_extrafieldschema_portals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="portals",
            field=models.ManyToManyField(blank=True, to="portals.portal"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="portals",
            field=models.ManyToManyField(blank=True, to="portals.portal"),
        ),
        migrations.AlterField(
            model_name="extrafieldschema",
            name="portals",
            field=models.ManyToManyField(blank=True, to="portals.portal"),
        ),
    ]
