# Generated by Django 4.1.4 on 2022-12-12 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fund",
            old_name="management_company",
            new_name="company",
        ),
    ]
