# Generated by Django 4.1.4 on 2022-12-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_fund_portal_fund_portals"),
    ]

    operations = [
        migrations.AddField(
            model_name="fund",
            name="extra",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
