# Generated by Django 4.1.4 on 2022-12-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_fund_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="extra",
            field=models.JSONField(default={}),
        ),
    ]
