# Generated by Django 4.1.4 on 2022-12-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('products', '0006_alter_fund_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fund',
            name='portals',
            field=models.ManyToManyField(blank=True, to='sites.site'),
        ),
    ]
