# Generated by Django 4.1.4 on 2022-12-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_fund_extra_alter_fund_portals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='extra',
            field=models.JSONField(default=dict),
        ),
    ]
