# Generated by Django 4.1.4 on 2022-12-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_fund_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
