# Generated by Django 4.1.4 on 2022-12-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portals", "0001_initial"),
        ("products", "0010_alter_fund_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="portals",
            field=models.ManyToManyField(blank=True, to="portals.portal"),
        ),
    ]
